### ISSUE TITLE
Slider layout not behaving like the default Slider()

### ISSUE THREAD

**Issue by MrWaggel** [boeledi/RangeSlider#11]
**Problem:**
When you put a RangeSlider() underneath a default Slider(), the width doesn't match.
![before](https://user-images.githubusercontent.com/18574520/52186187-05a3cd00-2826-11e9-9c6e-ef6d387ad437.png)

**Possible solution**
In class file, change line 520
`static const double _overlayDiameter = _overlayRadius * 2.0;`
`static const double _overlayDiameter = _overlayRadius;`

and at line 733 under the ` void performResize() {}` method to preserve the correct height
`constraints.hasBoundedHeight ? constraints.maxHeight : _overlayDiameter,`
`constraints.hasBoundedHeight ? constraints.maxHeight : _overlayDiameter * 2,`
![after](https://user-images.githubusercontent.com/18574520/52186313-e0638e80-2826-11e9-993e-ac35f81f959d.png)

But I'm not sure if it creates the wanted behavior for other cases, if you want I'll generate a pull request.

Awesome library and great documentation by the way my Wallonian friend, much appreciated!
Greetings from the north

**Comment by boeledi** [comment]
Hi,  I just released version 1.1.0 which now integrates your changes.  Thanks for your contribution.
