### ISSUE TITLE
lowerValue and upperValue most be as String

### ISSUE THREAD

**Issue by mohrezani** [boeledi/RangeSlider#13]
hi
i want to set slider range for money range! and i cant set value as decimal format! I think it was better set as String :\

**Comment by boeledi** [comment]
Hi,

Could you please elaborate a bit more about the problem you are facing?
Especially, I don't understand your statement "I can't set value as decimal format"...

Thanks

**Comment by mohrezani** [comment]
I need to display the lowerValue and upperValue in the string format , for example : "1,000 euro" and "10,000 euro".
![slider](https://user-images.githubusercontent.com/24787810/53478902-2958dc80-3a8d-11e9-981d-a76225cf40f5.png)

**Comment by boeledi** [comment]
Hi, normally there is no longer any problem doing this with the version I posted on Feb 16th 2019 (version 1.1.0)

Use the valueIndicatorFormatter callback, as follows:

valueIndicatorFormatter: (int index, double value){
  return '${value.toStringAsFixed(0)} euro';
}

This should solve your issue.  For more information, have a look at the example.

Regards,

**Comment by mohrezani** [comment]
> Hi, normally there is no longer any problem doing this with the version I posted on Feb 16th 2019 (version 1.1.0)
> 
> Use the valueIndicatorFormatter callback, as follows:
> 
> valueIndicatorFormatter: (int index, double value){
> return '${value.toStringAsFixed(0)} euro';
> }
> 
> This should solve your issue. For more information, have a look at the example.
> 
> Regards,

thanks :)
