### ISSUE TITLE
AndroidX?

### ISSUE THREAD

**Issue by kbrmimbyl** [boeledi/RangeSlider#21]
Hi, thanks for a great plugin! I'm using this in a project which we're migrating to AndroidX. Is this plugin already migrated? I couldn't find any info in the changelog on pub...

**Comment by boeledi** [comment]
Hi

Normally nothing needs to be changed as this packages compiles together
with the application. It is pure Dart/Flutter

Regards

**Comment by kbrmimbyl** [comment]
Superb, thanks! Maybe worth mentioning this somewhere on the changelog....
